version: '3.8'

services:
  # Main Application - Production
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: acquisitions_app_prod
    ports:
      - "3002:3002"
    env_file:
      - .env.production
    networks:
      - acquisitions_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3002/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Security and resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    # Run as non-root user for security
    user: "1001:1001"
    # Prevent privilege escalation
    security_opt:
      - no-new-privileges:true
    # Use read-only filesystem where possible
    read_only: true
    tmpfs:
      - /tmp
      - /var/tmp
    # Drop all capabilities
    cap_drop:
      - ALL

networks:
  acquisitions_network:
    driver: bridge
