name: Lint and Format

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  lint-and-format:
    name: ESLint and Prettier Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true
        id: eslint

      - name: Run Prettier check
        run: npm run format:check
        continue-on-error: true
        id: prettier

      - name: Annotate ESLint issues
        if: steps.eslint.outcome == 'failure'
        run: |
          echo "::error title=ESLint Issues Found::ESLint found issues in your code. Run 'npm run lint:fix' to automatically fix some issues."

      - name: Annotate Prettier issues
        if: steps.prettier.outcome == 'failure'
        run: |
          echo "::error title=Prettier Issues Found::Prettier found formatting issues. Run 'npm run format' to fix formatting issues."

      - name: Fail if issues found
        if: steps.eslint.outcome == 'failure' || steps.prettier.outcome == 'failure'
        run: |
          echo "::error::Code quality checks failed. Please fix the issues and try again."
          exit 1